In [150]:
import pandas as pd
import numpy as np

In [152]:
df = pd.read_csv("/Users/ethantsao/NBADraft1/nbaplayersdraft.csv")

In [154]:
df

,id,year,rank,overall_pick,team,player,college,years_active,games,minutes_played,...,3_point_percentage,free_throw_percentage,average_minutes_played,points_per_game,average_total_rebounds,average_assists,win_shares,win_shares_per_48_minutes,box_plus_minus,value_over_replacement
0,1,1989,1,1,SAC,Pervis Ellison,Louisville,11.0,474.0,11593.0,...,0.050,0.689,24.5,9.5,6.7,1.5,21.8,0.090,-0.5,4.4
1,2,1989,2,2,LAC,Danny Ferry,Duke,13.0,917.0,18133.0,...,0.393,0.840,19.8,7.0,2.8,1.3,34.8,0.092,-0.9,4.9
2,3,1989,3,3,SAS,Sean Elliott,Arizona,12.0,742.0,24502.0,...,0.375,0.799,33.0,14.2,4.3,2.6,55.7,0.109,0.2,13.5
3,4,1989,4,4,MIA,Glen Rice,Michigan,15.0,1000.0,34985.0,...,0.400,0.846,35.0,18.3,4.4,2.1,88.7,0.122,0.8,24.9
4,5,1989,5,5,CHH,J.R. Reid,UNC,11.0,672.0,15370.0,...,0.135,0.716,22.9,8.5,5.0,1.0,22.5,0.070,-2.9,-3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1917,1918,2021,56,56,CHO,Scottie Lewis,Florida,1.0,2.0,7.0,...,NaN,0.500,3.5,0.5,0.0,0.5,0.0,0.164,6.0,0.0
1918,1919,2021,57,57,CHO,Bal≈°a Koprivica,Florida State,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1919,1920,2021,58,58,NYK,Jericho Sims,Texas,1.0,41.0,555.0,...,NaN,0.414,13.5,2.2,4.1,0.5,1.5,0.128,-1.7,0.0
1920,1921,2021,59,59,BRK,RaiQuan Gray,Florida State,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1921,1922,2021,60,60,IND,Georgios Kalaitzakis,NaN,1.0,13.0,214.0,...,0.385,0.467,16.5,6.6,1.6,0.9,-0.1,-0.024,-7.0,-0.3

In [156]:
import pandas as pd

# Load the first DataFrame
df = pd.read_csv("/Users/ethantsao/NBADraft1/nbaplayersdraft.csv")

# Rename columns to match the second DataFrame
df_processed = df.rename(columns={
    'player': 'Player',
    'team': 'Team',
    'games': 'GP',
    'average_minutes_played': 'MPG',
    'points_per_game': 'PPG',
    'field_goal_percentage': 'FG%',
    '3_point_percentage': '3P%',
    'free_throw_percentage': 'FT%',
    'average_total_rebounds': 'RPG',
    'average_assists': 'APG',
    # Add other columns if available in the first DataFrame
})

# Calculate missing columns if necessary
# For example, if 'FGM' (field goals made) and 'FGA' (field goals attempted) are not available,
# you can calculate them using 'points_per_game' and 'field_goal_percentage'.
# However, since these columns are not directly available in the first DataFrame, we'll skip them.

# Drop unnecessary columns
columns_to_keep = [
    'Player', 'Team', 'GP', 'MPG', 'PPG', 'FG%', '3P%', 'FT%', 'RPG', 'APG', 'overall_pick'
]
df_processed = df_processed[columns_to_keep]

# Handle missing values
df_processed = df_processed.fillna({
    'GP': df_processed['GP'].mean(),
    'MPG': df_processed['MPG'].mean(),
    'PPG': df_processed['PPG'].mean(),
    'FG%': df_processed['FG%'].mean(),
    '3P%': df_processed['3P%'].mean(),
    'FT%': df_processed['FT%'].mean(),
    'RPG': df_processed['RPG'].mean(),
    'APG': df_processed['APG'].mean()
})

df_processed = df_processed.round(3)

In [158]:
df_2025 = pd.read_csv("/Users/ethantsao/NBADraft1/103NBAProspects.csv")

df_2025

,Player,Team,GP,MPG,PPG,FGM,FGA,FG%,3PM,3PA,3P%,FTM,FTA,FT%,ORB,DRB,RPG,APG,SPG,BPG
0,Ace Bailey,RUTG,20,34.0,20.2,7.7,16.4,0.468,2.0,5.2,0.385,2.9,4.3,0.674,2.1,5.7,7.8,1.0,1.1,1.4
1,Cooper Flagg,DUKE,21,32.0,20.0,6.6,13.7,0.484,1.3,3.9,0.346,5.4,6.7,0.801,1.5,6.4,8.0,4.2,1.5,1.2
2,Kam Jones,MARQ,22,33.3,19.0,7.7,15.6,0.493,1.7,5.4,0.322,1.9,2.9,0.667,0.8,3.7,4.5,6.2,1.6,0.2
3,Tre Johnson,TEXAS,20,32.7,19.0,6.7,14.9,0.450,2.5,6.5,0.377,3.1,3.5,0.886,0.2,2.6,2.7,2.3,1.0,0.4
4,Dylan Harper,RUTG,19,31.5,18.6,6.5,13.4,0.488,1.6,4.8,0.337,3.9,5.6,0.708,1.0,3.8,4.8,4.1,1.1,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98,Rocco Zikarsky,BRI,20,12.2,4.7,1.8,3.6,0.500,0.1,0.3,0.200,1.0,1.6,0.625,1.5,2.0,3.5,0.3,0.3,0.7
99,Kanaan Carlyle,IU,18,19.2,4.6,1.8,6.3,0.292,0.7,3.2,0.224,0.2,0.7,0.333,0.3,1.4,1.8,1.6,0.6,0.2
100,Joan Beringer,COL,36,16.5,4.1,1.7,2.9,0.590,0.0,0.0,0.000,0.7,1.2,0.595,1.5,2.8,4.3,0.3,0.4,1.2
101,Michael Ruzic,JOV,12,15.3,4.1,1.6,3.4,0.463,0.4,1.5,0.278,0.5,1.3,0.375,0.6,1.3,1.9,0.3,0.3,0.5
102,Hugo Gonzalez,RMB,34,9.9,3.2,1.1,2.6,0.400,0.4,1.3,0.295,0.7,1.0,0.727,0.4,1.4,1.8,0.6,0.2,0.4

In [160]:
columns_to_keep = ["Player", "Team", "GP", "MPG", "PPG", "FG%", "3P%", "FT%", "RPG", "APG"]

# Select only the columns to keep
df_2025_processed = df_2025[columns_to_keep]

# Display the processed DataFrame
df_2025_processed

             Player   Team  GP   MPG   PPG    FG%    3P%    FT%  RPG  APG
0        Ace Bailey   RUTG  20  34.0  20.2  0.468  0.385  0.674  7.8  1.0
1      Cooper Flagg   DUKE  21  32.0  20.0  0.484  0.346  0.801  8.0  4.2
2         Kam Jones   MARQ  22  33.3  19.0  0.493  0.322  0.667  4.5  6.2
3       Tre Johnson  TEXAS  20  32.7  19.0  0.450  0.377  0.886  2.7  2.3
4      Dylan Harper   RUTG  19  31.5  18.6  0.488  0.337  0.708  4.8  4.1
..              ...    ...  ..   ...   ...    ...    ...    ...  ...  ...
98   Rocco Zikarsky    BRI  20  12.2   4.7  0.500  0.200  0.625  3.5  0.3
99   Kanaan Carlyle     IU  18  19.2   4.6  0.292  0.224  0.333  1.8  1.6
100   Joan Beringer    COL  36  16.5   4.1  0.590  0.000  0.595  4.3  0.3
101   Michael Ruzic    JOV  12  15.3   4.1  0.463  0.278  0.375  1.9  0.3
102   Hugo Gonzalez    RMB  34   9.9   3.2  0.400  0.295  0.727  1.8  0.6

[103 rows x 10 columns]

In [162]:
df_processed

,Player,Team,GP,MPG,PPG,FG%,3P%,FT%,RPG,APG,overall_pick
0,Pervis Ellison,SAC,474.000,24.500,9.500,0.510,0.050,0.689,6.700,1.500,1
1,Danny Ferry,LAC,917.000,19.800,7.000,0.446,0.393,0.840,2.800,1.300,2
2,Sean Elliott,SAS,742.000,33.000,14.200,0.465,0.375,0.799,4.300,2.600,3
3,Glen Rice,MIA,1000.000,35.000,18.300,0.456,0.400,0.846,4.400,2.100,4
4,J.R. Reid,CHH,672.000,22.900,8.500,0.472,0.135,0.716,5.000,1.000,5
...,...,...,...,...,...,...,...,...,...,...,...
1917,Scottie Lewis,CHO,2.000,3.500,0.500,0.437,0.272,0.500,0.000,0.500,56
1918,Bal≈°a Koprivica,CHO,348.043,18.134,7.276,0.437,0.272,0.717,3.194,1.551,57
1919,Jericho Sims,NYK,41.000,13.500,2.200,0.722,0.272,0.414,4.100,0.500,58
1920,RaiQuan Gray,BRK,348.043,18.134,7.276,0.437,0.272,0.717,3.194,1.551,59
1921,Georgios Kalaitzakis,IND,13.000,16.500,6.600,0.463,0.385,0.467,1.600,0.900,60

In [164]:
df_processed.to_csv('df_processed.csv', index=False)
df_2025_processed.to_csv('df_2025_processed.csv', index=False)